import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#10141a",
        "on-background": "#dfe2eb",
        surface: "#10141a",
        "surface-dim": "#10141a",
        "surface-bright": "#353940",
        "surface-variant": "#31353c",
        "surface-container-lowest": "#0a0e14",
        "surface-container-low": "#181c22",
        "surface-container": "#1c2026",
        "surface-container-high": "#262a31",
        "surface-container-highest": "#31353c",
        "on-surface": "#dfe2eb",
        "on-surface-variant": "#becab9",
        "inverse-surface": "#dfe2eb",
        "inverse-on-surface": "#2d3137",
        outline: "#889484",
        "outline-variant": "#3e4a3d",
        "surface-tint": "#6fdd78",
        primary: "#6fdd78",
        "on-primary": "#00390e",
        "primary-container": "#34a547",
        "on-primary-container": "#00320b",
        "inverse-primary": "#006e23",
        secondary: "#7bd0ff",
        "on-secondary": "#00354a",
        "secondary-container": "#00a6e0",
        "on-secondary-container": "#00374d",
        tertiary: "#f9bd22",
        "on-tertiary": "#402d00",
        "tertiary-container": "#b88900",
        "on-tertiary-container": "#372700",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#8bfb91",
        "primary-fixed-dim": "#6fdd78",
        "on-primary-fixed": "#002106",
        "on-primary-fixed-variant": "#005319",
        "secondary-fixed": "#c4e7ff",
        "secondary-fixed-dim": "#7bd0ff",
        "on-secondary-fixed": "#001e2c",
        "on-secondary-fixed-variant": "#004c69",
        "tertiary-fixed": "#ffdf9f",
        "tertiary-fixed-dim": "#f9bd22",
        "on-tertiary-fixed": "#261a00",
        "on-tertiary-fixed-variant": "#5c4300",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "32px",
        xl: "64px",
        gutter: "24px",
        "container-max": "1000px",
      },
      fontFamily: {
        "display-code": ["var(--font-jetbrains-mono)", "monospace"],
        "code-lg": ["var(--font-jetbrains-mono)", "monospace"],
        "code-md": ["var(--font-jetbrains-mono)", "monospace"],
        "code-sm": ["var(--font-jetbrains-mono)", "monospace"],
        "ui-header": ["var(--font-geist)", "system-ui", "sans-serif"],
        "ui-body": ["var(--font-geist)", "system-ui", "sans-serif"],
        "ui-label": ["var(--font-geist)", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-code": [
          "32px",
          { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "500" },
        ],
        "code-lg": ["24px", { lineHeight: "36px", fontWeight: "400" }],
        "code-md": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "code-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "ui-header": [
          "16px",
          { lineHeight: "24px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "ui-body": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "ui-label": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
      maxWidth: {
        "container-max": "1000px",
      },
      keyframes: {
        "pulse-caret": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
      },
      animation: {
        "pulse-caret": "pulse-caret 1s ease-in-out infinite",
        "fade-in": "fade-in 200ms ease-out",
      },
    },
  },
  plugins: [],
};

export default config;
